# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-us'

# Website info
name: 'Go-Vader blog'
description: "Write a bit about Golang and other stuff"

short_url: 'https://www.go-vader.io'
google_analytics: UA-131843975-1
disqus: govader
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: ''


# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag

# gems and other configs
plugins: [jekyll-paginate]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...



exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - node_modules
  - .git
